# Generated by Django 5.0.6 on 2024-09-14 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('telegram_id', models.CharField(max_length=100)),
                ('grade', models.CharField(blank=True, choices=[('student', 'student'), ('junior', 'junior'), ('junior+', 'junior+'), ('middle', 'middle'), ('senior', 'senior'), ('lead', 'lead++')], max_length=100)),
                ('description', models.TextField()),
                ('skills_user', models.ManyToManyField(blank=True, to='project_management_app.skill')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
